apiVersion: v1
kind: Secret
metadata:
  name: streaming-secret
type: Opaque
stringData:
  JWT_SECRET: "super-secret-assignment-token-key-12345"
  AWS_ACCESS_KEY_ID: "ASIAXKD22AH4KWTDJGT2"
  AWS_SECRET_ACCESS_KEY: "tGzocWcPqL1HqBNnyxeCPEcmMg5DBtOuM/BtIYly"
