apiVersion: v1
kind: Secret
metadata:
  name: streaming-secret
type: Opaque
stringData:
  JWT_SECRET: "super-secret-assignment-token-key-12345"
  AWS_ACCESS_KEY_ID: "YOUR_MOCK_OR_REAL_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "YOUR_MOCK_OR_REAL_SECRET_KEY"
