apiVersion: v1
kind: Secret
metadata:
  name: streaming-secret
type: Opaque
stringData:
  JWT_SECRET: "super-secret-assignment-token-key-12345"
  AWS_ACCESS_KEY_ID: "ASIAXKD22AH4DIYJGNER"
  AWS_SECRET_ACCESS_KEY: "ObrEG/k/+tAXmyHdrLTTVK4NAxAygkkXexEKJe1X"
